if(NOT CMAKE_DUSK_COMPILE_OBJECT)
  set(CMAKE_DUSK_COMPILE_OBJECT
    "<CMAKE_DUSK_COMPILER> <SOURCE> <FLAGS> -o <OBJECT>")
endif()

if(NOT CMAKE_DUSK_LINK_EXECUTABLE)
  set(CMAKE_DUSK_LINK_EXECUTABLE
    "${CMAKE_COMMAND} -E copy <OBJECTS> <TARGET> && chmod +x <TARGET>")
endif()

set(CMAKE_DUSK_INFORMATION_LOADED 1)
